## Bag of Words (Bigram Approach)

In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame( {'text':['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output':[1,1,0,0]} )

In [3]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

### n-gram_range for implementing Bigram approach

In [7]:
cv = CountVectorizer(ngram_range=(2, 2))

In [12]:
bow = cv.fit_transform(df['text']) 

In [13]:
# vocab

print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [14]:
print(bow[0].toarray())

[[0 0 1 0 1 0]]


In [15]:
print(bow[1].toarray())

[[1 0 0 0 1 0]]


In [16]:
print(cv.transform(['campusx watch and write comment of campusx']).toarray())

# campusx watch : 1, campusx write : 0, people watch : 0, people write': 0, watch campusx : 0,  write comment : 1

[[1 0 0 0 0 1]]


## Bag of Words (Unigram & Bigram Approach)

### n-gram_range for implementing Unigram & Bigram approach

In [17]:
cv = CountVectorizer(ngram_range=(1, 2))

In [18]:
bow = cv.fit_transform(df['text']) 

In [19]:
# vocab

print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [20]:
print(bow[0].toarray())

[[1 0 0 0 1 1 0 1 1 0 0]]


In [21]:
print(bow[1].toarray())

[[2 1 0 0 0 0 0 1 1 0 0]]


In [22]:
print(cv.transform(['campusx watch and write comment of campusx']).toarray())

# campusx : 2, campusx watch : 1, campusx write : 0, comment : 1, people : 0,  people watch : 0 , people write': 0, watch : 1, 
# watch campusx : 0, write : 1, witecomment : 1

[[2 1 0 1 0 0 0 1 0 1 1]]
